### PR TITLE
WIP for Django 1.9 compatibility 

### PR DESCRIPTION
**Pull request by carltongibson**
**NOT READY TO MERGE**

I was hoping to quickly address any 1.9 issues... no such luck. 

I've opened the PR now because some locally I'm getting some passes and some failures. I want to see what it looks like on Travis, and hopefully get some input.

### CODE REVIEW

**Comment by carltongibson** [comment]
With 1.4 EOL and 1.7 only a month or two away, I'm wondering if it's time to rip out a lot of the old stuff and just say, "this is compressor going forward" — 1.8, 1.9 only, or such? 

(I get the feeling keeping this stuff running is not time well spent.)

**Comment by carltongibson** [comment]
Ah, OK. I take it back — for some reason I'm getting a local failure for `py34-1.9.X` (due to coffin) but this is passing on Travis. ... — and of course, now my local failure is passing too... (.pyc files no doubt...)

**Comment by karyon** [comment]
@carltongibson i opened https://github.com/django-compressor/django-compressor/issues/664 with the intention to remove some of the old cruft. i also asked @diox whether i should remove all references to coffin and jingo (there only tests and docs, no actual code), but he said no.

while jingo might still be used, coffin is really and truly obsolete, as stated by the author himself, see this comment: https://github.com/coffin/coffin/issues/62#issuecomment-93985275. if it would mean additional code to support django 1.9 in compressor while keeping the tests with coffin running, i'm even more in favor of removing at least coffin (and we're at it, jingo as well. i always say if people really need this, they can use an older version of compressor.)

**Comment by carltongibson** [comment]
OK. I've closed this since it's not going anywhere. 

#678 fixes the SortedDict issue from #675. 

@karyon Bar the `overextends` issue, at the moment it looks like the failures I was seeing were artefacts 

* so no need to rip everything out just yet :-) 
* but I would like to think about when we can remove some of this old stuff. 
* Once 1.7 is EOL we can probably start to think about it 
* but I'm not a Jingo user 
* and a lot of people are
* we need to get their input.
* I'd assumed everyone would switch to Django's own support over third-party packages 
* Is this the case?

@diox: You've been working with compressor for since these things were added, what's your view?

**Comment by karyon** [comment]
well, 1.7 EOL is due this december... and again my point is, jingo users can continue using compressor 1.5 forever :)

@carltongibson maybe you could join us in irc?

**Comment by diox** [comment]
I'm no longer terribly opposed to removing coffin and jingo support seeing it'd help us remove some cruft and they are not really maintained anyway. However, we need a clear, working jinja2 alternative for the users. Maybe with django-jinja ? I am not sure bare jinja is a good idea, but I haven't used jinja with compressor anyway so I don't really know

**Comment by carltongibson** [comment]
>  I haven't used jinja with compressor

No. That's that issue. No-one who does is hanging around. :-(

**Pull request closed without merging**
