### PR TITLE
Remove support for python 2.7, 3.4 and django 2.1

### PR DESCRIPTION
**Pull request by albertyw**
Depends on #966 

Drop support for python 2 - EOL January 1, 2020
Drop support for django 2.1 - EOL December 2019
Drop support for python 3.4 - EOL March 2019

### CODE REVIEW

**Comment by karyon** [comment]
django 1.11 is supported until april 2020 and supports python 2.7 and 3.4. Personally i would either support django 1.11 and all the respective python versions, or not support django 1.11 at all. 

I would be fine with dropping support for django 1.11 and python 2.7 and 3.4 ahead of schedule, but then i'd also vote for calling it 3.0 so we can simply say "django-compressor 2.x is the last version to support all of that".

**Comment by diox** [comment]
Yeah I also commented that I'm in favor of naming it 3.0 in #966. I don't mind Dropping Django 1.11 for that.

**Comment by albertyw** [comment]
Python 2 is EOL earlier than django 1.11 so I think python 2 support should be dropped now and django 1.11 later.  

I can also split this PR to have one PR that adds support for Django 3 and Python 3.8 and another PR that drops support for python 2, django 2.1, and python 3.4.  See also https://github.com/django-compressor/django-compressor/pull/964#issuecomment-561275170

**Comment by karyon** [comment]
I understand, but I disagree. Not supporting the python versions that django 1.11 supports means that we're not fully supporting django 1.11. There's no need for us to make it harder than necessary for downstream developers to figure out which django and python versions they can use, and we can make it simpler by sticking to the policy of our "parent" project as we've done in the past. Also, dropping python 2.7 support now and django 1.11 support later would mean more major releases with breaking changes for us.

So, I'd prefer to do a release now without breaking changes, and doing a 3.0 release without django 1.11 support, without python 2.7 support, and without six later (when it's done at the earliest :) ). @diox, I guess in the end it's your call since you're actually doing it :)

**Comment by diox** [comment]
Yep, let's not make it more complex that it needs to be. I don't mind fully dropping 1.11 and Python 2 together in our 3.0 release, it'll make things more straightforward, and we're going to do a 2.4 release that keeps that compatibility before anyway.

**Comment by albertyw** [comment]
I'm under the impression that django 1.11 implicitly drops support of python 2 when python 2 stops being supported itself, because python is the "parent project" of django.  I definitely get not having a lot of version churn just to add/drop support for dependencies of django-compressor though.  

I'll leave the decision to @diox though.  I can split this PR.

**Comment by jrief** [comment]
@karyon With Django-3.0 I removed Python-2.7 support from my many other projects but not for Django-1.11. Django-1.11 is a LTS and still supported until 2020/Q2, so that IMO should be kept.

In practice, we removed all occurrences of `six`, removed the `from __future__ import unicode_literals` and fix class inheritance and the super-calls. Django-1.11 had no problems with that, so in my opinion it would be safe to support Django-1.11–3.0 and Python-3.5–3.8 with the exception of Python-3.5+Django-3.0.

**Comment by debdolph** [comment]
Any progress on this?

**Comment by karyon** [comment]
see https://github.com/django-compressor/django-compressor/pull/964 for the plan (that PR is also the next one to be merged. do you need this PR for anything in particular?

**Comment by debdolph** [comment]
django-compressor is a dependency of django-dbbackup :).

**Pull request merged**
