### PR TITLE
Apply CssAbsoluteFilter to generated CSS even when COMPRESS_ENABLED is False

### PR DESCRIPTION
**Pull request by greghball**
When COMPRESS_ENABLED is False, and applying pre-compilers to produce CS......S, apply the CssAbsoluteFilter input method if that filter is configured in settings.COMPRESS_CSS_FILTERS.

Without this filter, any urls with relative paths in the LESS/SASS/SCSS etc. source will be broken in the output, making pre-compilation useless.

### CODE REVIEW

**Comment by karyon** [comment]
@diox, do you still think a setting is required? imo this is not magical and arbitrary at all. when django-compressor changes file locations (e.g. by precompiling them), it should take care that file paths inside the moved files stay valid.

although i'd do that a bit differently, maybe give filter a param `filters` which is self.cached_filters for the original two callers and CssAbsoluteFilter for the added call.

what do you say?

**Comment by diox** [comment]
@karyon : can you submit a pull request with that idea ? I've warmed up to the idea of not having an extra setting ; I'm still not quite sure how the right way would look like, but a new pull request would be helpful to restart the discussion.

**Comment by karyon** [comment]
yes, will do, hopefully later today.

**Comment by diox** [comment]
Closing in favor of #653.

**Pull request closed without merging**
