### PR TITLE
Remove Django 1.5 and 1.6 from tox and travis

### PR DESCRIPTION
**Pull request by carltongibson**
As per discussion on django-compressor/django-appconf#23

### CODE REVIEW

**Comment by karyon** [comment]
while you are at it, could you decide on dropping support on python 2.6? the last release is two years old and it's not supported anymore since then. this would make it easier to fix some of the newer deprecation warnings.

**Comment by diox** [comment]
Django 1.4 LTS support ends on October 1st. I was considering making a release in the next couple of weeks, but we could wait a little and drop Django 1.4. That'll also allow us to drop Python 2.6.

**Comment by carltongibson** [comment]
I'll follow this up adding coverage of Django master and such but thought I'd knock this out whilst I had 10 mins. 

If no-one shouts in the next half hour I'll merge this.

**Comment by karyon** [comment]
well, you could drop support for django 1.4 and python 2.6 right away. i don't see much benefit of waiting for the 1st october.

**Comment by carltongibson** [comment]
@karyon I think we'd rather wait. (I do see your point of view)

**Comment by karyon** [comment]
sure, your choice.

**Comment by carltongibson** [comment]
@karyon 👍 — Great work on all the refactoring BTW!

**Pull request merged**
