### PR TITLE
Specify mode explicitly to GzipFile constructor to fix FutureWarning.

### LINKED ISSUE #1018: FutureWarning: GzipFile
Using Python 3.9 and received this FutureWarning

`/usr/local/lib/python3.9/site-packages/compressor/storage.py:73: FutureWarning: GzipFile was opened for writing, but this will change in future Python releases.  Specify the mode argument for opening it for writing.
`

https://github.com/django-compressor/django-compressor/blob/2.4/compressor/storage.py#L73

Not critical but seems easy enough to fix.

https://docs.python.org/3/library/gzip.html#gzip.GzipFile

Just needs a mode applied.

### PR DESCRIPTION
**Pull request by tirkarthi**
Fixes #1018

### CODE REVIEW

**Comment by karyon** [comment]
thanks! unfortunately, there's a linter error.

**Comment by tirkarthi** [comment]
My bad, should be fixed now.

**Comment by karyon** [comment]
Thanks!

**Comment by tirkarthi** [comment]
Thanks @karyon

**Comment by webtweakers** [comment]
Nice, any idea when this will be released?

**Comment by diox** [comment]
You can follow the milestone here: https://github.com/django-compressor/django-compressor/milestone/10 and generally testing the `develop` branch helps getting releases out of the door faster.

**Pull request merged**
