### PR TITLE
Update RJSMIN version

### PR DESCRIPTION
**Pull request by Dhruvacube**
Rsjsmin 1.2.0 was released recently, so I updated the ver

### CODE REVIEW

**Comment by carltongibson** [comment]
@Dhruvacube thanks for this. It seems to have upset the tests. Do you have the bandwidth to look into that?

**Comment by Dhruvacube** [comment]
hey @carltongibson sorry I am dumb could you please explain what you meant by "Do you have the bandwidth to look into that?"

**Comment by carltongibson** [comment]
I just mean, do you have time to look at it? ("Bandwidth" here meaning personal time or energy, rather than anything technical.)

**Comment by Dhruvacube** [comment]
> I just mean, do you have time to look at it? ("Bandwidth" here meaning personal time or energy, rather than anything technical.)

Ohhhhhhh 😅, welll not rn but yeah after a few days I will sure look and update you 👍

**Comment by carltongibson** [comment]
Thanks. Happy to update the dependency if we can get the tests passing.

**Comment by cuu508** [comment]
@carltongibson at a glance, the test failures here look similar to the ones I tracked down and fixed in this PR: https://github.com/django-compressor/django-compressor/pull/1079

**Comment by carltongibson** [comment]
@cuu508 Sorry, that slipped my radar. I didn't notice you'd made the PR. Looking now...

**Review by carltongibson — APPROVED** [review]
OK, this looks good. Thanks @Dhruvacube

**Comment by Dhruvacube** [comment]
> 

anyways thanks, actually I was about to look into tests today, then saw the discussion, anyways thanks :)

**Pull request merged**
