### PR TITLE
Allow unicode in error message

### PR DESCRIPTION
**Pull request by logston**

### CODE REVIEW

**Comment by karyon** [comment]
as far as i understand, this should not change anything since we have `from __future__ import unicode_literals` in the file. additionally, i was not able to reproduce any error or broken characters with the current code. what was the problem you were trying to solve?

**Comment by logston** [comment]
Hmmm. I don't have the exact error anymore but it contained the following string:

```
u"\u2018env\u2019"
```

And the Django command "compress" failed to correctly raise the `CommandError` error.

**Comment by logston** [comment]
Happy to close this if you feel it is unnecessary. Just wanted to do my due diligence to give back.

**Comment by karyon** [comment]
yeah and i'm grateful for that :) i just don't understand why your change fixes your problem, as we have that import there which should make all string literals unicode... if you could investigate, that would be nice, because i could not reproduce any such error. otherwise, i can do nothing more than close this...

**Comment by logston** [comment]
Sorry, I don't have the time right now to replicate the error. Next time I'll save it!

**Pull request closed without merging**
