### PR TITLE
#750 CompilerFilter fails with UnicodeDecodeError when cache is used

### PR DESCRIPTION
**Pull request by akolpakov**
Fix bug #750.

### CODE REVIEW

**Comment by karyon** [comment]
hey, any chance you can whip up a test for that analogous to the one in #312?

**Comment by akolpakov** [comment]
Done!
Test with emulation of memcached which returns string regardless that we set unicode to it.

**Comment by karyon** [comment]
thanks! i'll have to bother you once more, but could you make the test provoke the actual failure (the crash)? right now (as far as i can see) it asserts that some string has some type, but that itself wouldn't be a problem if some other part didn't crash because of that. or am i misunderstanding something?

**Comment by akolpakov** [comment]
Yes. This is the cause of crash. Crash log itself you can see in bug #750.
But this is unit tests, which check only particular small functionality. I don't see the reason to put such huge test which includes chain which cross-cover whole plugin.

**Comment by karyon** [comment]
alright, thanks!

**Pull request merged**
