### PR TITLE
Fixing CssAbsoluteFilter changes double quotes to single quotes which causes svg to fail

### LINKED ISSUE #738: CssAbsoluteFilter changes double quotes to single quotes which causes svg to fail
CssAbsoluteFilter converts

```
url("data:image/svg+xml;utf8,<svg xmlns='http://www.w3.org/2000/svg' xmlns:xlink='http://www.w3.org/1999/xlink' x='0px' y='0px' width='25px' height='25px' viewBox='0 0 25 25' enable-background='new 0 0 25 25' xml:space='preserve'><rect id='XMLID_1_' x='4.9' y='10.9' fill='#18235D' width='15' height='3'/></svg>") no-repeat center
```
into this
```
url('data:image/svg+xml;utf8,<svg xmlns='http://www.w3.org/2000/svg' xmlns:xlink='http://www.w3.org/1999/xlink' x='0px' y='0px' width='25px' height='25px' viewBox='0 0 25 25' enable-background='new 0 0 25 25' xml:space='preserve'><rect id='XMLID_1_' x='4.9' y='10.9' fill='#18235D' width='15' height='3'/></svg>') no-repeat center
```

and Chrome says the property is invalid. I'm guessing this is because of the single quotes that are in the svg. To work around this problem, I just set
```
COMPRESS_CSS_FILTERS = []
```

### PR DESCRIPTION
**Pull request by intellisense**
Fixes #738

### CODE REVIEW

**Comment by karyon** [comment]
thanks! i should've mentioned that right away but unfortunately forgot it, i need a test before including this. basically, something like running the AbsoluteFilter on that svg and ensuring the correct outcome, and then doing the same with " and ' exchanged and ensuring the correct outcome once more.

**Comment by karyon** [comment]
hey, do you think there is any chance i get some tests from you in the next few weeks? :)

**Comment by intellisense** [comment]
@karyon Sorry for the delay, was pretty busy in the work. I will write tests on coming weekend. Thanks!

**Comment by karyon** [comment]
awesome, thanks!

**Comment by intellisense** [comment]
@karyon The URL wrapped with single quotes was already being tested [here](https://github.com/django-compressor/django-compressor/blob/develop/compressor/tests/test_filters.py#L280) so I added a one new test to check URL wrapped with double quotes should return a URL wrapped with double quotes.

During testing I found a new issue, consider this valid CSS which uses SVG URL:

```
body { background-image: url("data:image/svg+xml;utf8,<svg xmlns='http://www.w3.org/2000/svg' width='10' height='10'><linearGradient id='gradient'><stop offset='10%' stop-color='%23F00'/><stop offset='90%' stop-color='%23fcc'/> </linearGradient><rect fill='url(%23gradient)' x='0' y='0' width='100%' height='100%'/></svg>");}
```

The [URL_PATTERN](https://github.com/django-compressor/django-compressor/blob/develop/compressor/filters/css_default.py#L9) will choke and resulting in an improper match because it will stop at first closing parentheses `)` and gives:

```
"data:image/svg+xml;utf8,<svg xmlns='http://www.w3.org/2000/svg' width='10' height='10'><linearGradient id='gradient'><stop offset='10%' stop-color='%23F00'/><stop offset='90%' stop-color='%23fcc'/> </linearGradient><rect fill='url(%23gradient
```

Instead of returning the full URL till `</svg>"` because if you check the SVG has `fill` property which is also a URL. Should I file a separate issue? (This requires we should not be using regex to match URL pattern because we need to remember all the opening parenthesis or we should handle SVG separately altogether)

Thanks!

**Comment by karyon** [comment]
nice, thanks. yes please file a new issue for that. could you squash all the commits into one? otherwise it looks good.

**Comment by intellisense** [comment]
@karyon Squashed the commits into one. Thanks!

**Pull request merged**
