### PR TITLE
Add 2.1.1 changes

### LINKED ISSUE #820: No changelog or git tag for version 2.1.1
Hi! I see on PyPI that version 2.1.1 was released yesterday, but there's no git tag for this version, nor a changelog entry. I assume that's a mistake?

### PR DESCRIPTION
**Pull request by carltongibson**
Closes #820

### CODE REVIEW

**Comment by carltongibson** [comment]
@diox — I put these on `master` but they'd merge to `develop` just as well.

**Comment by carltongibson** [comment]
Vale.

**Comment by carltongibson** [comment]
Do you mind if I push straight to develop, or shall I do a PR?

**Comment by diox** [comment]
I don't mind, you know what you're doing :)

**Comment by carltongibson** [comment]
(I hope so 😅)

**Pull request merged**
