### PR TITLE
Handle TypeError from import_module

### LINKED ISSUE #569: "TypeError: relative imports require the 'package' argument" with preprocessor command that contains a dot
The following setting causes a `TypeError` when trying to import it, and does not use it as a command:

    COMPRESS_PRECOMPILERS = (
        ('text/x-scss', './foo ./bar'),
    )

This gets split by `mod_name, cls_name = get_mod_func(filter_or_command)` into:

    ipdb> mod_name
    './foo'
    ipdb> cls_name
    'bar'

I have a test case and fix for this, which I'll submit later.

### PR DESCRIPTION
**Pull request by blueyed**
Fixes #569 

The tests might need some improvements / restructuring.

### CODE REVIEW

**Comment by blueyed** [comment]
Any feedback on this?
Just found the PR again and rebased it.

**Comment by carltongibson** [comment]
This looks good — what a tricky error.

My only thought is that I can't see the TypeError being exercised in the covering tests, so we might never spot what catching it is for, once we forget I mean. Can the example  be made explicit?

**Comment by blueyed** [comment]
> I can't see the TypeError being exercised in the covering tests

It's because it gets turned into another error (FilterError).

> Can the example be made explicit?

Which example?  The test itself?

I could imagine setting up a test where TypeError gets thrown explicitly, but that should get done for every place where `import_module` is being used.

**Comment by diox** [comment]
Thanks for this, tests look good enough for me.

**Comment by carltongibson** [comment]
@blueyed Looking at the test I had to work out how it related to the issue. I thought that the sands of time  might obscure it. Maybe a comment would be all that's needed. 

Don't worry now though, it passed committee. :-)

**Comment by blueyed** [comment]
@carltongibson 
I see your point, yes.  Feel free to add additional documentation.. :)

Thanks for reviewing and merging!

**Pull request merged**
