### PR TITLE
remove silent exception catching

### PR DESCRIPTION
**Pull request by karyon**
extracted from #652 for easier bughunting.

### CODE REVIEW

**Comment by karyon** [comment]
weird, tests are green. maybe the refactoring in the other PR interfered with it. will investigate tomorrow.

**Comment by karyon** [comment]
i couldn't repro this anymore, even when going back to the original PR including the refactorings.

the failures seemed to be dependent on the test execution order, so i had a look whether some tests maybe change some settings inappropriately, and lo and behold, half of them did. I added a commit which fixes that, I hope I got them all.

**Comment by diox** [comment]
Excellent, thank you for this.

**Comment by karyon** [comment]
...i just checked, coverage changed slightly, at least for py34-1.8.X, one additional line and two branches are missed. that may or may not be a bad thing, i'm not sure... if you think some test might not work anymore like it should, tell me where i should start investigating...

**Comment by diox** [comment]
I'm not worried about it. We should probably re-renable coveralls though...

**Comment by carltongibson** [comment]
>  We should probably re-renable coveralls though...

I've seen codecov.io come in on Django Rest Framework and Crispy Forms, and I have to say it's great. (Much better experience re noise, and features, than coveralls.) @treyhunner — any chance I can ask you to open the same "Add CodeCov" pull request here that you've done elsewhere? 

That's an aside — pending that we should probably re-renable coveralls here...

**Comment by treyhunner** [comment]
@carltongibson yes I'm be happy to make a pull request adding CodeCov :smile_cat: 

I'll work on this in the next couple days.

**Pull request merged**
