### PR TITLE
Upgrade to latest rJSmin

### PR DESCRIPTION
**Pull request by hhaidar**
* Upgrade rJSmin to 1.0.10
* Pass in 'Keep Bang Comments' arg to rJSmin (see #399)

### CODE REVIEW

**Comment by diox** [comment]
Sounds like a good idea. Please fix the flake8 errors, thanks !

**Comment by hhaidar** [comment]
@diox yup, sorry about that

**Comment by diox** [comment]
Thanks!

**Comment by hhaidar** [comment]
@diox thank you so much. Do you have an ETA for the next tag?

**Comment by diox** [comment]
Nothing planned at the moment. There has not been enough changes yet to warrant a new release, IMHO.

**Pull request merged**
