### PR TITLE
Fix build

### PR DESCRIPTION
**Pull request by carltongibson**
These two should get the build passing again...

### CODE REVIEW

**Comment by carltongibson** [comment]
Well, that worked but it looks like coveralls will never report.

**Comment by diox** [comment]
Thanks!

**Comment by carltongibson** [comment]
No worries. 

As per comment on #588, I'm happy to help maintain here if you need it.

**Comment by diox** [comment]
Can you swing by #django-compressor IRC channel on freenode ? It'll be easier to discuss.

**Comment by carltongibson** [comment]
@diox — Sorry missed this. Have IRC open now.

**Pull request merged**
