### PR TITLE
Update rcssmin to 1.1.3 and rjsmin to 1.2.3

### PR DESCRIPTION
**Pull request by browniebroke**
Adding support for Python 3.13

### CODE REVIEW

**Comment by browniebroke** [comment]
Covered in https://github.com/django-compressor/django-compressor/pull/1264

**Comment by carltongibson** [comment]
@browniebroke Ah, but you correctly updated setup.py. If you wanted to pull in the JS min version too, I'd prefer yours still 😊

**Comment by browniebroke** [comment]
> If you wanted to pull in the JS min version too, I'd prefer yours still 😊

I think it's all done? Let me know if I missed another place... (or if you want me to squash)

**Review by carltongibson — APPROVED** [review]
Great. Thanks @browniebroke 🎁

**Pull request merged**
