### PR TITLE
Added Django 4.0 to test matrix.

### PR DESCRIPTION
**Pull request by carltongibson**

### CODE REVIEW

**Comment by carltongibson** [comment]
Hey @diox. 👋

There's these two `compressor.tests.test_offline.OfflineCompressTestCaseWithLazyStringAlikeUrls` which started failing across the board [a few months ago](https://github.com/django-compressor/django-compressor/actions) — not quite sure what's going on there 🤔 — but everything else is green for Django 4.0a1.

**Comment by carltongibson** [comment]
OK, I don't really understand these failures yet...

There are two failures across the board there — every version, not just 4.0 — which are a bit mysterious — there's no obvious cause, and the tests are a bit hard to decipher — I'm thinking that there much have been a change in a dependency ≈4 months ago but current status is 🤔

(I haven't worked out yet how to debug the writen manifest...)

**Comment by diox** [comment]
Yeah I noticed we started getting more or less random failures after switching to GitHub actions, but I haven't had the time to investigate yet. It's possible it's a minor detail in some dependency as you suggest. I will try to take a closer look soon.

**Comment by carltongibson** [comment]
I get the failures locally. 

I'm not sure what the issue is yet, or how to debug it exactly. 😅

**Comment by carltongibson** [comment]
@diox if your local venv passes, could you diff it exactly to a fresh one? That might show the dependency change (if that's the problem)

**Comment by carltongibson** [comment]
OK, all green after #1079 👯

**Pull request merged**
