### PR TITLE
Don't continue when raising a `UnicodeDecodeError`

### PR DESCRIPTION
**Pull request by mattrobenolt**
Don't continue executing more code, by adding a `continue` to start the loop over. :)

### CODE REVIEW

**Comment by diox** [comment]
Closing per lack of reply.

**Comment by mattrobenolt** [comment]
@diox This is still a bug fwiw, and the patch is super simple. So not sure why this was closed.

**Comment by diox** [comment]
It was closed because there had not been a reply in over a year, and it had no tests and wasn't applying to latest `develop` branch. I'll gladly merge it if those 2 issues are fixed!

**Comment by mattrobenolt** [comment]
I can happily apply to the `develop` branch, but not sure how to test this since I'm not intimate with the code base. The logic is trivial and this was obviously a typo when originally written since every other `except` statement has a `continue` which ends up resulting in a fatal `NameError` on `template` not existing.

We see this in our CI builds all the time.

**Comment by mattrobenolt** [comment]
@diox I just rebased and pushed to my branch, but the PR didn't update now since it's closed, but the commit is mattrobenolt/django-compressor@31454b072c95c492bce401df3e705c1ffe04db92

**Comment by diox** [comment]
Ok, I can't re-open the PR, so can you submit a new PR with that please ?

**Pull request closed without merging**
