### PR TITLE
Defer non-critical CSS

### PR DESCRIPTION
**Pull request by brunoprograma**
Defer non-critical CSS

### CODE REVIEW

**Comment by jsumnerPhD** [comment]
Just a quick question: is this ok for csp with the inline script in the online attribute?

**Comment by brunoprograma** [comment]
I honestly don't know anything about this policy. The suggestion was in the role of developer, following the Google Developers usage guidance given in the Lighthouse report. Check #1044

**Comment by brunoprograma** [comment]
> Just a quick question: is this ok for csp with the inline script in the onload attribute?

I honestly don't know anything about this policy. The suggestion was made following the Google Developers usage guidance given in the Lighthouse report. Check #1044

**Comment by diox** [comment]
> Just a quick question: is this ok for csp with the inline script in the onload attribute?

It's not.

**Comment by diox** [comment]
Hi,

Thanks for the PR, but I'm going to reject it:
- This was opened before we got to discuss whether or not it's a good idea in the django-compressor app itself (I don't think it is, because it introduces inline script)
- Tests are not passing
- There should be docs, because it's not necessarily the expected behavior.

You're welcome to customize that template in your own project if you want to preload css this way.

**Pull request closed without merging**
